# Generated by Django 2.2.1 on 2019-06-05 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=30, null=True, verbose_name='消息服务器')),
                ('routing_key', models.CharField(max_length=10, null=True, verbose_name='队列名称')),
                ('user', models.CharField(max_length=10, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='密码')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '消息通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
